name = "athena"
main = "src/index.js"
compatibility_date = "2023-04-13"
keep_vars = true

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

#only for local dev
[env.dev.vars]
viaversion = "5.11.0"
viabackwards = "5.11.0"
viarewind = "4.1.3"
viafabricplus = "4.6.3"
